# Use root/example as user/password credentials
version: '3.1'

services:
    
  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  microstatemachine:
    build: .
    ports:
      - 8090:8080
    depends_on:
      - mongo