version: '3.1'

services:
    
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    networks:
      - microusernetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  microstatemachine:
    build: .
    ports:
      - 8090:8080
    networks:
      - microusernetwork
    depends_on:
      - mongo

networks:
  microusernetwork:
    driver: bridge